// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

extern "C"{
SEXP rcpp_loglik( SEXP Y_obs, SEXP del_obs, SEXP V_eps, SEXP V_xi, SEXP Rho, SEXP mu_int, SEXP C_int) ;
}
RcppExport SEXP hngm_rcpp_loglik(SEXP Y_obs, SEXP del_obs, SEXP V_eps, SEXP V_xi, SEXP Rho, SEXP mu_int, SEXP C_int) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_loglik(Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int));
    return __result;
END_RCPP
}

extern "C"{
SEXP rcpp_loglik_tv(SEXP Y_obs, SEXP t_obs, SEXP V_eps, SEXP Rho, SEXP Nu0, SEXP Nu1, SEXP V_xi, SEXP Mu00, SEXP C00, SEXP T0) ;
}
RcppExport SEXP hngm_rcpp_loglik_tv(SEXP Y_obs, SEXP t_obs, SEXP V_eps, SEXP Rho, SEXP Nu0, SEXP Nu1, SEXP V_xi, SEXP Mu00, SEXP C00, SEXP T0) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_loglik_tv(Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0));
    return __result;
END_RCPP
}

extern "C"{
SEXP rcpp_sample_mu( SEXP Y_obs, SEXP del_obs, SEXP V_eps, SEXP V_xi, SEXP Rho, SEXP mu_int, SEXP C_int, SEXP Z_mat) ;
}
RcppExport SEXP hngm_rcpp_sample_mu(SEXP Y_obs, SEXP del_obs, SEXP V_eps, SEXP V_xi, SEXP Rho, SEXP mu_int, SEXP C_int, SEXP Z_mat) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_sample_mu(Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int, Z_mat));
    return __result;
END_RCPP
}

extern "C"{
SEXP rcpp_sample_tv_mu(SEXP Y_obs, SEXP t_obs, SEXP V_eps, SEXP Rho, SEXP Nu0, SEXP Nu1, SEXP V_xi, SEXP Mu00, SEXP C00, SEXP T0, SEXP Z_mat) ;
}
RcppExport SEXP hngm_rcpp_sample_tv_mu(SEXP Y_obs, SEXP t_obs, SEXP V_eps, SEXP Rho, SEXP Nu0, SEXP Nu1, SEXP V_xi, SEXP Mu00, SEXP C00, SEXP T0, SEXP Z_mat) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_sample_tv_mu(Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0, Z_mat));
    return __result;
END_RCPP
}


