# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_loglik <- function(Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int) {
    .Call('hngm_rcpp_loglik', Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int, PACKAGE = 'NGM')
}

rcpp_sample_mu <- function(Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int, Z_mat) {
    .Call('hngm_rcpp_sample_mu', Y_obs, del_obs, V_eps, V_xi, Rho, mu_int, C_int, Z_mat, PACKAGE = 'NGM')
}

rcpp_loglik_tv <- function(Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0) {
    .Call('hngm_rcpp_loglik_tv', Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0, PACKAGE = 'NGM')
}

rcpp_sample_tv_mu <- function(Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0, Z_mat) {
    .Call('hngm_rcpp_sample_tv_mu', Y_obs, t_obs, V_eps, Rho, Nu0, Nu1, V_xi, Mu00, C00, T0, Z_mat, PACKAGE = 'NGM')
}